[package]
name = "game_maps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
crossbeam = "0.8"
